plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/nishanm1/Library/CloudStorage/GoogleDrive-nishansinghkaler786@gmail.com/My Drive/TTE Shared Drive 2024/Lighthouse"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]